name: flutter_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^3.1.0
  http: ^0.12.0+2
  webfeed: ^0.4.2
  json_annotation: ^2.4.0
  cupertino_icons: ^0.1.2
  dio: 2.0.22

  retrofit: any
  logger: any  #for logging purpose



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  retrofit_generator: any


flutter:
  uses-material-design: true